# Generated by Django 2.0.7 on 2022-04-05 22:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_auto_20220405_2344'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('empAuth_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
