# Generated by Django 2.0.7 on 2022-04-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_auto_20220406_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
